image: "node:latest"

before_script:
  - yarn

stages:
  - test
  - release

test:
  stage: test
  script:
    - yarn test

release:
  stage: release
  variables:
    NODE_ENV: production
  script:
    - yarn release
