image: "node:latest"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/
  - yarn.lock

before_script:
  - yarn

stages:
  - test
  - release

test:
  stage: test
  script:
    - yarn test

release:
  stage: release
  variables:
    NODE_ENV: production
  script:
    - yarn release
